### ISSUE TITLE
Exclude NYT gift links

### ISSUE THREAD

**Issue by grbray** [whoneedsabudget/fixed-that-for-you#11]
Exclude the bot from fixing gift links as they are already free to view.

Example of a link -

https://www.nytimes.com/2024/08/16/technology/apple-epic-spotify-app-stores.html?unlocked_article_code=1.EU4._QkR.xPx1J6VnTnCy&smid=url-share

**Comment by techguydave** [comment]
Thanks, fixed in https://github.com/whoneedsabudget/fixed-that-for-you/commit/2c427457d0464bc448fef4b7c3e833a3e26339a2.
