### ISSUE TITLE
Add BlueSky support

### ISSUE THREAD

**Issue by grbray** [whoneedsabudget/fixed-that-for-you#14]
https://github.com/Rapougnac/VixBluesky

Fix with bskyx.app

**Comment by grbray** [comment]
Please make priority to fix.  P1, Sev1, etc.  urgent.  @techguydave

**Comment by grbray** [comment]
When do you think this will be done @techguydave ?

**Comment by grbray** [comment]
Hi! This is a work stoppage item for just me.  Can you please prioritize it over all the rest of your work @techguydave ?

**Comment by grbray** [comment]
Disregard.  I think I can do it manually by adding an x.  Please take your time and at your leisure.

**Comment by techguydave** [comment]
If you'd like the feature so badly please open a pull request.
